### ISSUE TITLE
Compatability with pytest pytest-xdist==1.30.0

### ISSUE THREAD

**Issue by therefromhere** [pytest-dev/pytest-randomly#201] opened 2019-10-02 02:11 UTC
FYI I think there's a compatibility issue with pytest-xdist==1.30.0, see https://github.com/pytest-dev/pytest-xdist/issues/472

**Comment by adamchainz** [comment] 2019-10-02 15:34
We don't currently test with xdist, if you are working on this I think it'd be good to have some tests here using it.

**Comment by thedrow** [comment] 2020-04-13 08:55
Seems like xdist works in 1.31.0.

**Comment by adamchainz** [comment] 2020-04-13 09:39
Thanks @thedrow . Will close this issue then.

**Comment by nodakai** [comment] 2020-04-15 01:56
No, the issue is still there (I'm not saying pytest-randomly has to do anything for this issue but just for the sake of recoding...)

test/test_0.py
```python
def test_a(): pass
```

test/test_1.py
```python
def test_b(): pass
```

```
$ while pytest -d --tx 2*popen test; do sleep 1; done
========================================== test session starts ===========================================
platform linux -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
Using --randomly-seed=1586915652
rootdir: /home/kai/tst
plugins: forked-1.1.3, randomly-3.2.1, xdist-1.31.0
gw0 [2] / gw1 [2]
collecting 0 items / 1 error                                                                             
================================================= ERRORS =================================================
__________________________________________ ERROR collecting gw1 __________________________________________
Different tests were collected between gw0 and gw1. The difference is:
--- gw0

+++ gw1

@@ -1,2 +1,2 @@

+test/test_0.py::test_a
 test/test_1.py::test_b
-test/test_0.py::test_a
======================================== short test summary info =========================================
ERROR gw1
============================================ 1 error in 0.37s ============================================
```

There's some indeterminacy here

**Closed** 2020-04-15 10:14 UTC

**Comment by adamchainz** [comment] 2020-04-15 10:15
Thanks for the example @nodakai . With that I was able to figure out what the problem was - the workers would *sometimes* not share the same default seed, since it's based on `int(time.time())` and sometimes workers would start across the second boundary. This is, of course, a random error 😂

Fixed in #245 and released in version 3.3.0 ! 🎲🎉

**Comment by therefromhere** [comment] 2020-04-15 10:26
Awesome!

**Comment by fermezz** [comment] 2020-05-12 15:24
@adamchainz would you guys be open to a contribution backporting this fix into the `1.2.x` branch?  Since https://github.com/pytest-dev/pytest/pull/6870 was merged, now `pytest-randomly` on version `1.2.x` –the one compatible with Python2– is incompatible with `pytest` version `>=4.6.10`

**Comment by adamchainz** [comment] 2020-05-12 20:27
I don't work with Python 2.7 more (at least, for free). If you want a backport please fork, cherry-pick the commit, and [pip install from your repo](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/).

**Comment by adamchainz** [comment] 2020-05-12 20:27
I don't work with Python 2.7 more (at least, for free). If you want a backport please fork, cherry-pick the commit, and [pip install from your repo](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/).
